name: Python test and deploy
on: [pull_request]

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Install project (incl. dev) dependencies
        run: |
          make devinstall
      - name: Write env variables to env.txt file
        run: |
          touch .env
          echo ELEPHANTSQL_URL=${{ secrets.ELEPHANTSQL_URL }} >> .env
      - name: Test with pytest
        run: make test